# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Upload SSL-related files
  when: gateway_application_upload_certs | bool
  block:
    - name: Create the gateway certificates directory
      ansible.builtin.file:
        name: "{{ gateway_certs_dir }}"
        state: directory
        owner: "{{ gateway_user }}"
        group: "{{ gateway_group }}"
        mode: "0755"

    - name: Copy application CA certificate file
      ansible.builtin.copy:
        src: "{{ gateway_application_local_ca_certificate_file }}"
        dest: "{{ gateway_application_ca_certificate_file }}"
        owner: "{{ gateway_user }}"
        group: "{{ gateway_group }}"
        mode: '0644'
      when:
        - gateway_application_local_ca_certificate_file is defined
        - gateway_application_local_ca_certificate_file is not none

    - name: Upload certs to servers
      when: gateway_application_mode == 'server'
      block:
        - name: Copy Gateway Manager certificate and key
          when: gateway_connect_enabled | bool
          block:
            - name: Copy Gateway manager certificate
              ansible.builtin.copy:
                src: "{{ gateway_connect_local_certificate_file }}"
                dest: "{{ gateway_connect_certificate_file }}"
                owner: "{{ gateway_user }}"
                group: "{{ gateway_group }}"
                mode: '0644'
              when:
                - gateway_connect_local_certificate_file is defined
                - gateway_connect_local_certificate_file is not none

            - name: Copy Gateway manager private key
              ansible.builtin.copy:
                src: "{{ gateway_connect_local_private_key_file }}"
                dest: "{{ gateway_connect_private_key_file }}"
                owner: "{{ gateway_user }}"
                group: "{{ gateway_group }}"
                mode: '0600'
              when:
                - gateway_connect_local_private_key_file is defined
                - gateway_connect_local_private_key_file is not none

        - name: REMOVEME
          ansible.builtin.debug:
            var: gateway_server_local_certificate_file

        - name: Copy Gateway server certificate
          ansible.builtin.copy:
            src: "{{ gateway_server_local_certificate_file }}"
            dest: "{{ gateway_server_certificate_file }}"
            owner: "{{ gateway_user }}"
            group: "{{ gateway_group }}"
            mode: '0644'
          when:
            - gateway_server_local_certificate_file is defined
            - gateway_server_local_certificate_file is not none

        - name: Copy Gateway server private key
          ansible.builtin.copy:
            src: "{{ gateway_server_local_private_key_file }}"
            dest: "{{ gateway_server_private_key_file }}"
            owner: "{{ gateway_user }}"
            group: "{{ gateway_group }}"
            mode: '0600'
          when:
            - gateway_server_local_private_key_file is defined
            - gateway_server_local_private_key_file is not none

    - name: Upload certs to runners
      when: gateway_application_mode == 'runner'
      block:
        - name: Copy Gateway runner certificate
          ansible.builtin.copy:
            src: "{{ gateway_runner_local_certificate_file }}"
            dest: "{{ gateway_runner_certificate_file }}"
            owner: "{{ gateway_user }}"
            group: "{{ gateway_group }}"
            mode: '0644'
          when:
            - gateway_runner_local_certificate_file is defined
            - gateway_runner_local_certificate_file is not none

        - name: Copy Gateway runner private key
          ansible.builtin.copy:
            src: "{{ gateway_runner_local_private_key_file }}"
            dest: "{{ gateway_runner_private_key_file }}"
            owner: "{{ gateway_user }}"
            group: "{{ gateway_group }}"
            mode: '0600'
          when:
            - gateway_runner_local_private_key_file is defined
            - gateway_runner_local_private_key_file is not none
