# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Upload SSL-related files
  when: gateway_application_upload_certs | bool
  block:
    - name: Create the gateway certificates directory
      ansible.builtin.file:
        name: "{{ gateway_certs_dir }}"
        state: directory
        owner: "{{ gateway_user }}"
        group: "{{ gateway_group }}"
        mode: "0755"

    - name: Copy application CA certificate file
      ansible.builtin.copy:
        src: "{{ gateway_application_local_certs_dir }}/{{ gateway_application_local_ca_certificate_filename }}"
        dest: "{{ gateway_application_ca_certs_dir }}/{{ gateway_application_ca_certificate_filename }}"
        owner: "{{ gateway_application_ca_certificate_owner }}"
        group: "{{ gateway_application_ca_certificate_group }}"
        mode: '0444'
      when:
        - gateway_application_local_ca_certificate_filename is defined
        - gateway_application_local_ca_certificate_filename is not none

    - name: Copy Gateway server certificate
      ansible.builtin.copy:
        src: "{{ gateway_application_local_certs_dir }}/{{ gateway_local_certificate_filename }}"
        dest: "{{ gateway_certs_dir }}/{{ gateway_certificate_filename }}"
        owner: "{{ gateway_user }}"
        group: "{{ gateway_group }}"
        mode: '0644'
      when:
        - gateway_local_certificate_filename is defined
        - gateway_local_certificate_filename is not none

    - name: Copy Gateway server private key
      ansible.builtin.copy:
        src: "{{ gateway_application_local_certs_dir }}/{{ gateway_local_private_key_filename }}"
        dest: "{{ gateway_certs_dir }}/{{ gateway_private_key_filename }}"
        owner: "{{ gateway_user }}"
        group: "{{ gateway_group }}"
        mode: '0400'
      when:
        - gateway_local_private_key_filename is defined
        - gateway_local_private_key_filename is not none

    - name: Upload Gateway Manager certificate and key
      when: gateway_application_mode == 'server'
      block:
        - name: Copy Gateway Manager certificate and key
          when: gateway_connect_enabled | bool
          block:
            - name: Copy Gateway manager certificate
              ansible.builtin.copy:
                src: "{{ gateway_application_local_certs_dir }}/{{ gateway_connect_local_certificate_filename }}"
                dest: "{{ gateway_certs_dir }}/{{ gateway_connect_certificate_filename }}"
                owner: "{{ gateway_user }}"
                group: "{{ gateway_group }}"
                mode: '0644'
              when:
                - gateway_connect_local_certificate_filename is defined
                - gateway_connect_local_certificate_filename is not none

            - name: Copy Gateway manager private key
              ansible.builtin.copy:
                src: "{{ gateway_application_local_certs_dir }}/{{ gateway_connect_local_private_key_filename }}"
                dest: "{{ gateway_certs_dir }}/{{ gateway_connect_private_key_filename }}"
                owner: "{{ gateway_user }}"
                group: "{{ gateway_group }}"
                mode: '0400'
              when:
                - gateway_connect_local_private_key_filename is defined
                - gateway_connect_local_private_key_filename is not none
