# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Validate Gateway variables
  tags: always
  block:
    - name: Validate certificate variables when uploading is configured on
      when: gateway_application_upload_certs | bool
      block:
        - name: Validate local certificate variables when uploading certificates is configured on
          ansible.builtin.assert:
            that:
              - gateway_application_local_certs_dir is defined
              - gateway_application_local_certs_dir is not none
              - gateway_application_local_ca_certificate_filename is defined
              - gateway_application_local_ca_certificate_filename is not none
              - gateway_local_certificate_filename is defined
              - gateway_local_certificate_filename is not none
              - gateway_local_private_key_filename is defined
              - gateway_local_private_key_filename is not none
            fail_msg: gateway_application_local_ca_certificate_filename, gateway_local_certificate_filename
                      and gateway_local_private_key_filename must be defined when
                      gateway_application_upload_certs is set to 'true'

        - name: Stat the local certificates directory
          ansible.builtin.stat:
            path: "{{ gateway_application_local_certs_dir }}"
          register: stat_result
          delegate_to: localhost
          become: false

        - name: Validate local certificates directory exists
          ansible.builtin.assert:
            that: stat_result.stat.exists
            fail_msg: Local certificates directory does not exist
