# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Upload SSL-related files
  when: gateway_pki_upload | bool
  block:
    - name: Create the gateway client certificates directory
      ansible.builtin.file:
        name: "{{ gateway_client_pki_dir }}"
        state: directory
        owner: "{{ gateway_client_user }}"
        group: "{{ gateway_client_group }}"
        mode: "0755"

    - name: Copy application CA certificate
      ansible.builtin.copy:
        src: "{{ gateway_client_pki_ca_cert_src }}"
        dest: "{{ gateway_client_pki_ca_cert_dest }}"
        owner: "{{ gateway_client_user }}"
        group: "{{ gateway_client_user }}"
        mode: "0444"
      when:
        - gateway_client_pki_ca_cert_src is defined
        - gateway_client_pki_ca_cert_src is not none

    - name: Copy client certificate
      ansible.builtin.copy:
        src: "{{ gateway_client_pki_cert_src }}"
        dest: "{{ gateway_client_pki_cert_dest }}"
        owner: "{{ gateway_client_user }}"
        group: "{{ gateway_client_user }}"
        mode: "0440"
      when:
        - gateway_client_pki_cert_src is defined
        - gateway_client_pki_cert_src is not none

    - name: Copy client private key
      ansible.builtin.copy:
        src: "{{ gateway_client_pki_key_src }}"
        dest: "{{ gateway_client_pki_key_dest }}"
        owner: "{{ gateway_client_user }}"
        group: "{{ gateway_client_group }}"
        mode: "0400"
      when:
        - gateway_client_pki_key_src is defined
        - gateway_client_pki_key_src is not none
