# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Validate Gateway variables
  tags: always
  block:
    - name: Validate gateway_client_packages is set
      ansible.builtin.assert:
        that:
          - gateway_client_packages is defined
          - gateway_client_packages is iterable
          - gateway_client_packages | length > 0
        fail_msg: gateway_client_packages must be defined

    - name: Validate gateway_secrets_encrypt_key is correctly formatted
      ansible.builtin.assert:
        that:
          - gateway_secrets_encrypt_key is match('^[0-9a-fA-F]+$')
          - gateway_secrets_encrypt_key | length == 64
        fail_msg: gateway_secrets_encrypt_key must be a 64 character hexadecimal string

    - name: Validate variables when uploading is configured on
      when: gateway_pki_upload | bool
      block:
        - name: Validate gateway_pki_src_dir variable is set
          ansible.builtin.assert:
            that:
              - gateway_pki_src_dir is defined
              - gateway_pki_src_dir is not none
            fail_msg: gateway_pki_src_dir must be defined when gateway_pki_upload is set to 'true'

        - name: Stat gateway_pki_src_dir directory
          ansible.builtin.stat:
            path: "{{ gateway_pki_src_dir }}"
          register: gateway_client_pki_dir_stat_result
          delegate_to: localhost
          become: false

        - name: Validate gateway_pki_src_dir exists
          ansible.builtin.assert:
            that: gateway_client_pki_dir_stat_result.stat.exists
            fail_msg:
              - "Local pki directory {{ gateway_pki_src_dir }} does not exist"
              - "Set gateway_pki_src_dir to a valid directory"
