# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
###########################
# Gateway connect variables
###########################

gateway_server_connect_enabled: true

gateway_server_connect_server_ha_enabled: false
gateway_server_connect_server_ha_is_primary: false

gateway_server_connect_insecure_tls: false
gateway_server_connect_certificate_file: "{{ gateway_server_pki_cert_dest }}"
gateway_server_connect_private_key_file: "{{ gateway_server_pki_key_dest }}"
