# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Install and configure IAG5 servers
  import_playbook: itential.iag5.iag5_server

- name: Install and configure IAG5 clients
  import_playbook: itential.iag5.iag5_client
